### ISSUE TITLE
Create a /version command to see what version or git commit the bot is currently running

### ISSUE THREAD

**Issue by boomer41** [SRTigers98/birthday-discord-bot#10]
Add a simple /version command to get the git commit or milestone the bot is running.
This is useful for CI deployments to see if that actually works.

**Comment by SRTigers98** [comment]
I would suggest to use the current version of the project, configured in the **build.gradle.kts** file, as output of the version command.

**Comment by boomer41** [comment]
The problem with that is, that we don't know whether bot running on the main branch was recently updated by the CI scripts.
Using the project version would result in "1.0.0-SNAPSHOT".

When building a milestone/tag, that tag name could automagically be used in the gradle file for the project version IMO.
