### ISSUE TITLE
Garbage Collection for unused Guilds

### ISSUE THREAD

**Issue by kef41719** [SRTigers98/birthday-discord-bot#2]
- When Bot leaves channel, internal data for this channel hast to be removed from the database
- Scheduler Tasks must be stopped

**Comment by SRTigers98** [comment]
According to the [discord commands and events](https://discord.com/developers/docs/topics/gateway#commands-and-events), there is **no event** that indicates the bot that he leaved a guild.
However, since a cleanup is needed, a new solution must be developed.

**Comment by SRTigers98** [comment]
To cleanup the database, a scheduled task should run once every week which checks all joined guilds of the bot.
If a guild is in the database the bot is no member anymore, all database entries referenced to this guild should be deleted.
