### ISSUE TITLE
Create a discord thread when sending out a reminder

### ISSUE THREAD

**Issue by boomer41** [SRTigers98/birthday-discord-bot#7]
When a reminder is sent out, the bot should automatically create a thread so that anyone can congratulate without spamming the main channel.

The thread should stay open for 24h or more.

**Comment by SRTigers98** [comment]
If two members of one guild have their birthday on the same day, should two separate threads be created, or only one thread per day?

**Comment by boomer41** [comment]
Two threads should be created because a thread should be attached to an initial message. Thus, only the first person would get a thread, the second person would have to hijack the first person's thread.
